import './globals.css'
import { Advent_Pro, Akshar, Albert_Sans } from 'next/font/google'
import Image from 'next/image'
import NavMenu from './components/NavMenu'

const inter = Albert_Sans({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  

  function handleMenuSelect(){
    console.log("hello world")
  }
  let buttonSize = 24


  return (
    <html lang="en" className='scroll-smooth bg-white'>
      <body className={`${inter.className} flex flex-col items-center bg-white transition-all`}>
        <nav className='bg-white max-w-5xl w-full'>
          <h1 className="animate-topFade text-3xl font-light text-black m-4">
            Madison<span className='font-bold'>Index</span>
          </h1>
        </nav>
        {children}
       <NavMenu/>
      </body>
    </html>
  )
}
