import './globals.css'
import {Albert_Sans } from 'next/font/google'
import Image from 'next/image'
import NavMenu from '../components/NavMenu'


const inter = Albert_Sans({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  
  return (
    <html lang="en" className='scroll-smooth bg-white'>
      <body className={`${inter.className} w-full flex flex-col items-center transition-all`}>
        <div className='w-full h-full bg-white flex items-center flex-col'>
            <nav className='bg-white max-w-5xl w-full flex justify-between items-center'>
              <h1 className="animate-topFade text-3xl font-light text-slate-800 m-4">
                Madison<span className='font-bold'>Index</span>
              </h1>
              <div className='animate-topFade overflow-hidden h-12 w-12 rounded-full border-2 border-indigo-300 mr-4 ml-4'>
                <Image
                src="/user.png"
                height={150}
                width={150}
                alt="user profile picture"
                />
              </div>
            </nav>
            {children}
            <div id="spacerforstaticmenu" className='h-24 w-full'></div>
          <NavMenu/>
        </div>
      </body>
    </html>
  )
}
